// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOFtNzMRFUqMSYj9e4TMe1vHYuRTdZ2hg',
    appId: '1:434712487042:web:ffac1e3e5bd881ab86009b',
    messagingSenderId: '434712487042',
    projectId: 'glud-1539d',
    authDomain: 'glud-1539d.firebaseapp.com',
    databaseURL: 'https://glud-1539d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'glud-1539d.appspot.com',
    measurementId: 'G-TM5X0W6V7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ExMbCNBfEcQlM_accGLY4WUJIt_MDMA',
    appId: '1:434712487042:android:b7915aa48329a01a86009b',
    messagingSenderId: '434712487042',
    projectId: 'glud-1539d',
    databaseURL: 'https://glud-1539d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'glud-1539d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpA4R1mxHgtyZ_Y6MEl0LSricR5RYTcdk',
    appId: '1:434712487042:ios:7a2833705621192686009b',
    messagingSenderId: '434712487042',
    projectId: 'glud-1539d',
    databaseURL: 'https://glud-1539d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'glud-1539d.appspot.com',
    androidClientId: '434712487042-cllgvmi0qqs34cefijr8k5j0mos59249.apps.googleusercontent.com',
    iosClientId: '434712487042-kq6tpq1bstabr7ds6tism8dpujp64tng.apps.googleusercontent.com',
    iosBundleId: 'com.glud.glud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpA4R1mxHgtyZ_Y6MEl0LSricR5RYTcdk',
    appId: '1:434712487042:ios:b787d5ebdda2d21c86009b',
    messagingSenderId: '434712487042',
    projectId: 'glud-1539d',
    databaseURL: 'https://glud-1539d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'glud-1539d.appspot.com',
    androidClientId: '434712487042-cllgvmi0qqs34cefijr8k5j0mos59249.apps.googleusercontent.com',
    iosClientId: '434712487042-ndrjiktftfi6e5n4hdujtgj9fipup92k.apps.googleusercontent.com',
    iosBundleId: 'com.glud.glud.RunnerTests',
  );
}
